name: Build Armbian
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Build Armbian
      uses: armbian/build@main
      with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token                 # userspace
          armbian_board:     "onecloud"                   # build targe
          armbian_release:   "jammy"
          armbian_target:    "build"
