name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install mdbook
      run: |
        uname -a
        openssl version -a
        ls /bin | grep openssl
  ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
    - name: Install mdbook
      run: |
        uname -a
        openssl version -a
        ls /bin | grep openssl
  ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
    - name: Install mdbook
      run: |
        uname -a
        openssl version -a
        ls /bin | grep openssl        
